# ТЕМА 10. Декораторы и исключения
Отчет по Теме # 10 выполнил(а):
- Жижанова Мария Вячеславовна
- ЗПИЭ 20-1

| Задание | Сам_раб |
| ------ |  ------ |
| Задание 1 | + | - |
| Задание 2 | + | - |
| Задание 3 | + | - |
| Задание 4 | + | - |
| Задание 5 | + | - |


знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.


## Самостоятельная работа №1

### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор.
### Подсказка: необходимо использовать модуль time Декоратор необходимо использовать для этой функции:

``` python
def fibonacci(): fib1 = fib2 = 1

for i in range(2, 200):
fib1, fib2 = fib2, fib1 + fib2 print(fib2, end=' ')

if		name	== '	main	': fibonacci()
```

### Результатом вашей работы будет листинг кода и скриншот консоли, в котором будет выполненная функция Фибоначчи и время выполнения программы. Также на этом примере можете посмотреть, что решение задач через рекурсию не всегда является хорошей идеей. Поскольку решение Фибоначчи для 100 с использованием рекурсии и без динамического программирования решается более десяти секунд, а решение точно такой же задачи, но через цикл for еще и для 200, занимает меньше 1 секунды.


```python
import time

def timing_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        execution_time = end_time - start_time
        print(f"Время выполнения функции {func.__name__}: {execution_time} секунд")
        return result
    return wrapper

@timing_decorator
def fibonacci():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
    print(fib2, end=' ')

if __name__ == '__main__':
    fibonacci()
```

![image](https://github.com/MariaZhizhanova/lab/assets/145640698/cf877563-236d-44e4-93e4-3e662b104602)

## Вывод
В данной задаче код вычисляет 200-ое число Фибоначчи, а затем выводит время, затраченное на выполнение этой операции.

  
## Самостоятельная работа №2

### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.


```python
def read_file (f_name):
    try:
        with open("пустой_файл.txt", "r") as file:
            f = file.read()
            if not f:
                raise Exception("Файл пустой")
            else:
                print(f)
    except FileNotFoundError:
        print("Файл не найден")
    except Exception as ex:
         print(ex)
f_name = "file.txt"
read_file(f_name)
```

![image](https://github.com/MariaZhizhanova/lab/assets/145640698/7712ff51-0cd5-4822-a5e2-e9f6444a76af)
![image](https://github.com/MariaZhizhanova/lab/assets/145640698/bf2181fb-12c2-4478-9039-2dfbbaaa9125)

## Вывод
В данной задача был написан, код который открывает файл для чтения, считывает его содержимое и проверяет, пустой ли он. Если файл пустой, то возникает исключение с сообщением "файл пустой", либо выводится содержимое файла. 


## Самостоятельная работа №3

### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль

```python
def add_two():
    user_input = input("Введите число: ")
    try:
        number = float(user_input)
        return 2 + number
    except (ValueError, TypeError):
        raise ValueError("Неподходящий тип данных.")
try:
    result = add_two()
    print(result)
except ValueError as e:
    print(e)
```

![image](https://github.com/MariaZhizhanova/lab/assets/145640698/1ed0001a-3462-491b-844d-8c8560c85cab)

## Вывод
Теперь программа запрашивает у пользователя ввод числа и обрабатывает введенные данные. Пожалуйста, попробуйте этот код и введите число при запросе.Этот код представляет собой простую программу на Python, которая запрашивает у пользователя ввод числа и затем пытается сложить это число с 2. Вот как работает каждая часть кода:


## Самостоятельная работа №4

### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
def log_function_call(func):
    def wrapper(*args, **kwargs):
        result = func(*args, **kwargs)
        with open('log.txt', 'a') as log_file:
            log_file.write(f"Вызвана функция {func.__name__} с аргументами {args} и ключевыми аргументами {kwargs}\n")
            log_file.write(f"Результат: {result}\n")
        return result
    return wrapper

@log_function_call
def multiply(a, b):
    return a * b

@log_function_call
def add(a, b):
    return a + b

result1 = multiply(3, 4)
result2 = add(5, 7)

print(f"Результат умножения: {result1}")
print(f"Результат сложения: {result2}")
```

![image](https://github.com/MariaZhizhanova/lab/assets/145640698/303d7c93-0afa-4534-855c-155dabb6cf9a)

## Вывод
В данной задаче код демонстрирует использование декоратора для логирования вызовов функций и их результатов. Логирование происходит в файле log.txt.


## Самостоятельная работа №5
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
class CustomException(Exception):
    pass

def divide(a, b):
    if b == 0:
        raise CustomException("Деление на ноль недопустимо")
    return a / b

try:
    result = divide(10, 0)
except CustomException as e:
    print(f"Поймано исключение: {e}")
else:
    print(f"Результат деления: {result}")

def process_data(data):
    if not data:
        raise CustomException("Пустые данные не допускаются")

try:
    data = []
    process_data(data)
except CustomException as e:
    print(f"Поймано исключение: {e}")
else:
    print("Данные обработаны успешно")
```

![image](https://github.com/MariaZhizhanova/lab/assets/145640698/e1954047-177c-4e8f-ae20-b0e8e7f8eb6d)

## Вывод
В данной задаче мы создаем класс CustomException, который наследуется от базового класса Exception. Затем он определяет две функции: divide и process_data.Код демонстрирует использование пользовательского исключения (CustomException) для обработки ситуаций, когда определенные условия не выполняются, и позволяет ловить их и выводить информативные сообщения об ошибках.

## Общие выводы по теме
В 10 на примерах изучили и получили практический опыт, как декораторы могут использоваться для управления и обработки исключений в Python. Они позволяют создавать гибкое и чистое управление исключениями в коде, что способствует улучшению его читаемости и обслуживаемости.
